// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqr4EctCfPXChcWSWNqEMYhuXbtLAGCDE',
    appId: '1:564084185113:android:e9838d9697af0d05dab288',
    messagingSenderId: '564084185113',
    projectId: 'solve-ur-shape',
    databaseURL: 'https://solve-ur-shape-default-rtdb.firebaseio.com',
    storageBucket: 'solve-ur-shape.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqiuTAQQ9AL7cZgaMKQxqtxwChN3pEKP8',
    appId: '1:564084185113:ios:f5dd666b11cfc2e7dab288',
    messagingSenderId: '564084185113',
    projectId: 'solve-ur-shape',
    databaseURL: 'https://solve-ur-shape-default-rtdb.firebaseio.com',
    storageBucket: 'solve-ur-shape.appspot.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
